### ISSUE TITLE
Creating meshes without textures is a little confusing

### ISSUE THREAD

**Issue by MisterPotter** [marovira/atlas#7]
Primarily talking about https://github.com/marovira/atlas/blob/master/source/atlas/utils/Mesh.cpp#L228. Here the if statement says if we have textures, but no attrib index for them, than we return. However, if we have no textures and we don't specify an index for textures (we want to render without textures), than we don't hit that code within the if statement and crash on an index out of error. Same applies for the normal check above

**Comment by MisterPotter** [comment]
I'd suggest just changing it to 
`if (!mImpl->hasNormals || arrays.size() < 2)` and similar for the other, if that's intended behavior. Who knows, it's 3:45 am

edit: I have a branch with the small changes if you want me to make a PR, I don't think I have access to create a branch though

**Comment by marovira** [comment]
I see what the problem is, and you're right in that we could end up with an index out of range error. The issue here is a bit more subtle than this though, and to be honest I hadn't really thought about it. Suppose that we don't have normals, so we don't specify a binding point, but we do have textures (which could contain the normal data) and we want to use them. The question becomes, how do we know we are not supposed to bind the normals but bind the textures? I need to think about this a bit more, but you are right that as it stands it is a bit confusing.
